In [1]:
from pycaret.classification import setup, compare_models, pull
import pandas as pd

In [2]:
df = pd.read_csv("../dataSet/final_dataset.csv", encoding='utf-8')
df.shape

(193002, 29)

In [ ]:
s = setup(data=df, target='churn', session_id=42, fix_imbalance=True)
compare_models()
results = pull()
print(results[['Model', 'Recall']].sort_values('Recall', ascending=False))

                                    Model  Recall
knn                K Neighbors Classifier  1.0000
rf               Random Forest Classifier  0.9993
et                 Extra Trees Classifier  0.9981
dt               Decision Tree Classifier  0.9931
qda       Quadratic Discriminant Analysis  0.9863
catboost              CatBoost Classifier  0.9822
nb                            Naive Bayes  0.9234
xgboost         Extreme Gradient Boosting  0.9132
lightgbm  Light Gradient Boosting Machine  0.7693
ridge                    Ridge Classifier  0.6429
lda          Linear Discriminant Analysis  0.6426
gbc          Gradient Boosting Classifier  0.6388
ada                  Ada Boost Classifier  0.6255
lr                    Logistic Regression  0.6238
svm                   SVM - Linear Kernel  0.4962
dummy                    Dummy Classifier  0.0000

In [ ]:
print(s.pipeline)

Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['cons_12m', 'cons_gas_12m',
                                             'cons_last_month', 'date_activ',
                                             'date_end', 'date_modif_prod',
                                             'date_renewal',
                                             'forecast_cons_12m',
                                             'forecast_cons_year',
                                             'forecast_discount_energy',
                                             'forecast_meter_rent_12m',
                                             'forecast_price_energy_p1',
                                             'forecast_...
                                    transformer=TargetEncoder(cols=['activity_new'],
                                                              drop_invariant=False,
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              hierarchy=None,
                                                              min_samples_leaf=20,
                                                              return_df=True,
                                                              smoothing=10,
                                                              verbose=0))),
                ('balance',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=FixImbalancer(estimator=SMOTE(k_neighbors=5,
                                                                              random_state=42,
                                                                              sampling_strategy='auto'))))],
         verbose=False)